name: ox
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.7.6
  - conda-forge::osmnx
  - conda-forge::flask
  - conda-forge::flask-restx
  - conda-forge::flask-sqlalchemy
  - conda-forge::psycopg2
  - conda-forge::pytest
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::black
  - conda-forge::isort
  - conda-forge::flask-admin
  - pytest-xdist
